apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-script
              image: docker.io/felixchen1998/web-watcher-check:latest

          restartPolicy: Never
