apiVersion: apps/v1
kind: Deployment
metadata:
  name: compare-deployment
  labels:
    app: compare-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compare-app
  template:
    metadata:
      labels:
        app: compare-app
    spec:
      containers:
        - name: compare-container
          image: docker.io/felixchen1998/web-watcher-compare:latest
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "400m"
          ports:
            - containerPort: 80
              protocol: TCP
