apiVersion: apps/v1
kind: Deployment
metadata:
  name: configure-deployment
  labels:
    app: configure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configure-app
  template:
    metadata:
      labels:
        app: configure-app
    spec:
      containers:
        - name: configure-container
          image: docker.io/felixchen1998/web-watcher-configure:latest
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: configure-secret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: configure-secret
                  key: password
            - name: SECRET_URL
              valueFrom:
                secretKeyRef:
                  name: configure-secret
                  key: url
