apiVersion: apps/v1
kind: Deployment
metadata:
  name: screenshot-deployment
  labels:
    app: screenshot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screenshot-app
  template:
    metadata:
      labels:
        app: screenshot-app
    spec:
      containers:
        - name: screenshot-container
          image: docker.io/felixchen1998/web-watcher-screenshot:latest
          ports:
            - containerPort: 80
              protocol: TCP
