apiVersion: v1
kind: Service
metadata:
  name: configure
  labels:
    app: configure
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8004
  selector:
    app: configure-app
