apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8005
      nodePort: 30001
  selector:
    app: frontend-app
