apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8008
      nodePort: 30002
  selector:
    app: gateway-app
