apiVersion: v1
kind: Service
metadata:
  name: token
  labels:
    app: token
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8008
      nodePort: 30002
  selector:
    app: token-app
