apiVersion: v1
kind: Service
metadata:
  name: screenshot-service
  labels:
    app: screenshot-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: screenshot-app
